### ISSUE TITLE
Kompelieren des Plugins

### ISSUE THREAD

**Issue by jstjst** [christophritterbach/StromWasserGas#1]
Ich würde gerne das Plugin ausprobieren, scheitere aber aktuell am kompelieren.
Ich habe mich versucht an dieser Anleitung entlang zu hangeln: https://www.willuhn.de/wiki/doku.php?id=develop:eclipse
In eclipse bekomme ich diverse Fehler. Ist es grundsätzlich möglich den aktuellen Stand zu kompleieren?
Ich bin leider in Java und eclipse nicht wirklich fit.

**Comment by christophritterbach** [comment]
Ehrlich gesagt, habe ich mich auch Schritt für Schritt an das Projekt herangewagt. Basis war für mich das Beispielprojekt von Olaf Willuhn,
Dann hatte ich begruffen, dass ich "nur" das ANT-Skript starten muss. Also muss man neben Java und Eclipse auch noch ant installieren und alles einrichten.
[jameica.energie.zip](https://github.com/christophritterbach/StromWasserGas/files/14438873/jameica.energie.zip)
Aber ich kann doch mal meine letzte Version anhängen.

**Comment by jstjst** [comment]
Danke für die schnelle Antwort, damit hat zumindest die Installation erstmal geklappt.
